---
  - name: Create grocy ZFS volume
    community.general.zfs:
      name: "{{ GROCY_STORAGE_ZFS_POOL }}/{{ GROCY_STORAGE_ZFS_FS }}"
      state: present
      extra_zfs_properties:
        mountpoint: "{{ GROCY_PATH }}"
